theme: jekyll-theme-dinky
markdown: kramdown

title: zorchp's Homepage
description: A college student love Python and TeX


# page_excerpts: true
show_info: true
# google_analytics:

info:
  csdn_url: https://blog.csdn.net/qq_41437512
  repository_url: http
  # another_url: another value
