baseurl: /
highlighter: rouge
math_engine: mathjax
safe: true
markdown: kramdown

theme: jekyll-text-theme

kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: ""

title: Zorch's Homepage
description: share some useful skills and tips


